<?php

/**
 * Define the sage roles.
 */
function sage_roles() {
  return array(
    'employee' => 'Employee',
    'partner' => 'Partner',
    'customer_level_3' => 'Customer - Level 3',
    'customer_level_2' => 'Customer - Level 2',
    'customer_level_1' => 'Customer - Level 1',
    'customer_off_plan' => 'Customer (off plan)',
    'student' => 'Student',
    'registered' => 'Registered',
  );
}

/**
 * Implements hook_permission()
 */
function sage_roles_permission() {
  $perms = array();
  foreach(sage_roles() as $key => $name) {
    $perms['access ' . $key . ' content'] = array(
      'title' => t('Access ' . $name . ' Content'),
      'description' => t('Access content assigned to the ' . $name . ' permission.'),
    );
  } 
  return $perms;
}

/**
 * Implements hook_bakery_transmit().
 */
function sage_roles_bakery_transmit($edit, $account, $category) {
  $roles = array_filter($edit['roles']);
  watchdog('bakery', 'transmit roles ' . serialize($roles));
  return !empty($roles) ? array('roles' => $roles) : array();
}

/**
 * Implements hook_bakery_receive().
 */
function sage_roles_bakery_receive($account, $fields) {
  watchdog('bakery', 'recieve roles ' . serialize($fields));
  if (isset($fields['data']['roles'])) {
    return user_save($account, array('roles' => $fields['data']['roles']));
  }
}