<?php
/**
 * @file
 * Code for the Enterprise News feature.
 */

include_once 'enterprise_news.features.inc';

/**
 * Implements hook_ds_classes_alter().
 * Provide the necessary classes for news types.
 */
function enterprise_news_ds_classes_alter(&$classes, $name) {
  if ('ds_classes_regions' === $name) {
    $classes['style-news-full'] = t('News: Full');
    $classes['style-news-teaser'] = t('News: Teaser');
    $classes['style-news-recent'] = t('News: Recent');
  }
}
