<?php

/**
 * Implementation of hook_form_BASE_FORM_ID_alter().
 */
function sage_premium_form_node_form_alter(&$form, &$form_state, $form_id) {
  $node = $form_state['node'];
  
  $perms = array('' => '');
  foreach(sage_roles() as $key => $name) {
    $perms['access ' . $key . ' content'] = $name;
  }

  $form['premium_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Premium Settings'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#weight' => 35,
    '#attributes' => array('class' => array('display_sidebar'))
  );
  
  // Check premium_perm so no errors pop up
  // Notice: Undefined property: stdClass::$premium_perm in sage_premium_form_node_form_alter() on line 32
  if (isset($node->premium_perm)) {
  	$premium_perm = $node->premium_perm;
  } else {
  	$premium_perm = NULL;
  }
  
  $form['premium_settings']['premium_perm'] = array(
    '#type' => 'select',
    '#title' => t('Permission Level'),
    '#default_value' => $premium_perm,
    '#options' => $perms,
    '#weight' => 2,
  );

  // Allow or not to override the premium option.
  // See http://drupal.org/project/override_node_options
  if (!user_access('administer nodes') && user_access('override '. $node->type .' premium option')) {
    $form['premium_settings']['premium_perm']['#access'] = TRUE;
  }
  
  // Move the default nopremium option
  $form['premium_settings']['premium'] = $form['options']['premium'];
  unset($form['options']['premium']);
}

/**
 * Implements hook_nopremium_access()
 */
function sage_premium_nopremium_access($node, $account) {
  if (isset($node->premium_perm) && $node->premium_perm) {
    return user_access($node->premium_perm, $account);
  }
}