<?php
/**
 * @file
 * Code for the Enterprise Press feature.
 */

include_once 'enterprise_press.features.inc';

/**
 * Implements hook_ds_classes_alter().
 * Provide the necessary classes for press types.
 */
function enterprise_press_ds_classes_alter(&$classes, $name) {
  if ('ds_classes_regions' === $name) {
    $classes['style-press-full'] = t('Press: Full');
    $classes['style-press-teaser'] = t('Press: Teaser');
  }
}
