<?php

/**
 * @file
 * Code for the Blog App feature.
 */
include_once('enterprise_blog_display.features.inc');

/**
 * Implements hook_ds_fields_info().
 */
function enterprise_blog_display_ds_fields_info($entity_type) {
  $node = array();
  $user = array();
  $node['blog_sticky_metainfo'] = array(
    'title' => t('Meta Information (Sticky)'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit' => array('enterprise_blog|*'),
    'function' => 'enterprise_base_blog_meta_info',
    'properties' => array(),
  );
  return array('node' => $node, 'user' => $user);
}

/**
 * Implements hook_styler().
 * 
 * Tell styler module what styles this module provides.
 */
function enterprise_blog_display_styler() {
  $styles = array();

  $styles['blog_teaser'] = array(
    'title' => 'Blog Teaser',
    'description' => t('Display Suite Layout: %layout', array('%layout' => 'Bootstrap > Two column stacked')),
    'element' => array(
      '#tag' => 'article',
      '#attributes' => array(
        'class' => 'style-article-teaser clearfix',
      ),
      '#value' => '
  <header class="ds-header">
    <img src="http://lorempixel.com/500/260" alt="Image" />
  </header>
  <section class="ds-left">' .
      theme('html_tag', $styles['date_stacked'])
      . '</section>
  <section class="ds-right">
    <h3 class="title">Here is a recent post that will go lower ...</h3>
    <div class="author">Author: <a rel="me" href="#">Kayla Wren</a></div>
    <div class="teaser">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin erat ipsum, commodo non commodo sit amet, porttitor quis est la di. <a href="#">Read More &gt;&gt;</a></div>
  </section>
',
    ),
  );

  $styles['blog_mini'] = array(
    'title' => 'Blog Mini',
    'description' => t('Display Suite Layout: %layout', array('%layout' => 'Bootstrap > Two column stacked')),
    'element' => array(
      '#tag' => 'article',
      '#attributes' => array(
        'class' => 'style-article-mini clearfix',
      ),
      '#value' => '
  <header class="ds-header">
    <img src="http://lorempixel.com/500/260" alt="Image" />
  </header>
  <section class="ds-left">' .
      theme('html_tag', $styles['date_stacked'])
      . '</section>
  <section class="ds-right">
    <h3 class="title">Here is a recent post that will go lower ...</h3>
    <div class="author">Author: <a rel="me" href="#">Kayla Wren</a></div>
  </section>
',
    ),
  );

  return $styles;
}

/**
 * Implements hook_VOCABULARY_NAME_uri() which is provided by enterprise_base.
 * 
 * @return array
 */
function enterprise_blog_display_blog_categories_uri_alter(&$url, $term) {
  $url['path'] = 'blog/category/' . enterprise_base_create_machine_name($term->name);
}

/**
 * Implements hook_VOCABULARY_NAME_uri() which is provided by enterprise_base.
 * 
 * @return array
 */
function enterprise_blog_display_blog_tags_uri_alter(&$url, $term) {
  $url['path'] = 'blog/tag/' . enterprise_base_create_machine_name($term->name);
}

