<?php

/**
 * @file
 * Ooyala module provides integration with the Ooyala video service.
 *
 * Ooyala integrates with CCK to provide a field, widget, and formatters to
 * upload video directly to the Ooyala service and display it.
 */

/**
 * Implements hook_menu().
 */
function ooyala_taxonomy_menu() {
  $items['admin/config/media/ooyala/sync-taxonomy'] = array(
    'title' => 'Ooyala Sync confirmation',
    'description' => 'Confirmation page before beginning taxonomy syncing.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ooyala_taxonomy_sync_confirm'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ooyala_taxonomy.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_node_insert().
 */
function ooyala_taxonomy_node_insert($node) {
  ooyala_taxonomy_node_sanitize($node);
}

/**
 * Implements hook_node_update().
 */
function ooyala_taxonomy_node_update($node) {
  ooyala_taxonomy_node_sanitize($node);
}

// Helper function for hook_node_insert and hook_node_update().
function ooyala_taxonomy_node_sanitize($node) {
  // This special flag is set when we're pulling information from Ooyala
  // on cron jobs. No point in sending information back to Ooyala that we
  // just got from them.
  if (empty($node->pulled_from_ooyala)) {
    module_load_include('inc', 'ooyala', 'includes/ooyala.api');

    // Send Ooyala the current labels.
    if ($ooyala_taxonomy = variable_get('ooyala_taxonomy', array())) {
      $labels = ooyala_taxonomy_node_labels($node);
      $embed_codes = ooyala_node_embed_codes($node);

      $existing_lids = array();
      foreach ($embed_codes as $embed_code) {
        $existing_labels = ooyala_api_video_label_load($embed_code);
        foreach ($existing_labels as $label) {
          $existing_lids[] = $label->id;
        }
      }

      // Remove labels that are no longer associated the asset.
      ooyala_api_video_label_remove($embed_codes, array_diff($existing_lids, $labels));

      // And add the labels that have been added.
      ooyala_api_video_label_add($embed_codes, array_diff($labels, $existing_lids));
    }
  }  
}

/**
 * Implements hook_taxonomy_term_insert().
 */
function ooyala_taxonomy_taxonomy_term_insert($term) {
  $ooyala_vocabularies = variable_get('ooyala_taxonomy', array());
  if (!empty($ooyala_vocabularies[$term->vid]) && empty($term->pulled_from_ooyala)) {
    $vocabulary_olid = $ooyala_vocabularies[$term->vid];
    // Check if needing to add this term to Ooyala. If $term->olid is already
    // set this term originated from Ooyala and doesn't need to be sent.
    // See ooyala_taxonomy_term_sync().
    if (!isset($term->olid)) {
      module_load_include('inc', 'ooyala', 'includes/ooyala.api');
      module_load_include('inc', 'ooyala_taxonomy', 'ooyala_taxonomy');
      $label = ooyala_taxonomy_create_label($term, $term->vid, $vocabulary_olid);
      if ($olid = ooyala_api_label_add($label)) {
        $term->olid = $olid;
      }
    }
    // Always add the entry in the ooyala_taxonomy table.
    if (isset($term->olid)) {
      ooyala_taxonomy_term_save($term);
    }
  }
}

/**
 * Implements hook_taxonomy_term_update().
 */
function ooyala_taxonomy_term_update($term) {
  module_load_include('inc', 'ooyala_taxonomy', 'ooyala_taxonomy');
  $ooyala_vocabularies = variable_get('ooyala_taxonomy', array());
  if ($ooyala_vocabularies[$term->vid] && empty($term->pulled_from_ooyala)) {
    $vocabulary_olid = $ooyala_vocabularies[$term->vid];

    // Load the Ooyala label ID and check for renamed terms.
    $term = reset(ooyala_taxonomy_term_load($term->tid));
    if (isset($term->olid)) {
      module_load_include('inc', 'ooyala', 'includes/ooyala.api');
      $old_label = ooyala_api_label_name($term->olid);
      $label = ooyala_taxonomy_create_label($term, $term->vid, $vocabulary_olid);
      if ($old_label != $label) {
        ooyala_api_label_rename($term->olid, $term->name);
        ooyala_taxonomy_term_save($term);
      }
    }
  }
}

/**
 * Save a taxonomy term's Ooyala information to the database.
 *
 * This function is called from ooyala_taxonomy_term_insert() and
 * ooyala_taxonomy_term_update().
 */
function ooyala_taxonomy_term_save($term) {
  static $time;
  $time = isset($time) ? $time : REQUEST_TIME;

  $update = !isset($term->updated) ? NULL : array('tid');
  $term->updated = $time;
  $term->olid = isset($term->olid) ? $term->olid : NULL;

  if ($term->tid && $term->olid) {
    db_merge('ooyala_taxonomy')
      ->key(array('tid' => $term->tid))
      ->fields(array('vid' => $term->vid, 'tid' => $term->tid, 'olid' => $term->olid, 'updated' => $term->updated))
      ->execute();
  }
}

/**
 * Implements hook_taxonomy_term_delete().
 */
function ooyala_taxonomy_term_delete($term) {
  $ooyala_vocabularies = variable_get('ooyala_taxonomy', array());
  if (!empty($ooyala_vocabularies[$term->vid])) {
    // Delete any matching Ooyala label information. We have to use a direct
    // query here instead of ooyala_taxonomy_term_load() because the term_data
    // record has already been deleted.
    $olid = db_select('ooyala_taxonomy', 'ot')
      ->fields('ot', array('olid'))
      ->condition('ot.tid', $term->tid)
      ->execute()
      ->fetchAssoc();
    if (isset($olid['olid'])) {
      module_load_include('inc', 'ooyala', 'includes/ooyala.api');
      ooyala_api_label_delete($olid['olid']);
      db_delete('ooyala_taxonomy')
        ->condition('tid', $term->tid)
        ->execute();
    }
  }
}

/**
 * Implementation of hook_taxonomy_vocabulary_delete().
 */
function ooyala_taxonomy_vocabulary_delete($vocabulary) {
  $ooyala_vocabularies = variable_get('ooyala_taxonomy', array());
  if ($ooyala_vocabularies[$vocabulary->vid]) {
    unset($ooyala_vocabularies[$vocabulary->vid]);
    variable_set('ooyala_taxonomy', $ooyala_vocabularies);
    db_delete('ooyala_taxonomy')
      ->condition('vid', $vocabulary->vid)
      ->execute();
    drupal_set_message(t('The vocabulary %name is no longer synced with Ooyala. Labels within Ooyala backlot have not been affected.', array('%name' => $vocabulary->name)));
  }
}

/**
 * Implements hook_cron().
 */
function ooyala_taxonomy_cron() {
  module_load_include('inc', 'ooyala_taxonomy');
  ooyala_taxonomy_term_sync_pull_labels();
}

/**
 * Implements hook_ooyala_create_node()
 */
function ooyala_taxonomy_ooyala_create_node(&$node, $video) {
  if (variable_get('ooyala_taxonomy', array()) && isset($video['labels'])) {
    module_load_include('inc', 'ooyala_taxonomy');
//    $node->taxonomy = array();
    $fields_to_check = ooyala_taxonomy_get_taxonomy_fields();
    foreach ($fields_to_check as $field_name) {
      if (isset($node->{$field_name})) {
        foreach ($video['labels'] as $olid => $label_path) {
          $node->{$field_name}[LANGUAGE_NONE][]['tid'] = ooyala_taxonomy_term_load(NULL, $olid);
        }
      }
    }
  }
}

/**
 * Implements hook_ooyala_sync_pull_videos().
 *
 * Update a list of nodes with any changed label information from Ooyala.
 */
function ooyala_taxonomy_ooyala_sync_pull_videos(&$nodes, $videos, $node_map) {
  module_load_include('inc', 'ooyala_taxonomy');
  // Make a regular expression that we can use to filter out non-synced labels.
  $ooyala_taxonomy = variable_get('ooyala_taxonomy', array());
  $vocabulary_labels = array();
  $label_filter = '';
  foreach ($ooyala_taxonomy as $vid => $vocabulary_olid) {
    $vocabulary_label = ooyala_api_label_name($vocabulary_olid);
    $vocabulary_labels[$vid] = preg_quote($vocabulary_label, '/');
  }
  $label_filter .= '/^' . implode('|', $vocabulary_labels) . '\//';

  foreach ($videos as $embed_code => $video) {
    foreach ($node_map['embed_codes'][$embed_code] as $nid) {
      $node = &$nodes[$nid];

      // On each node, get the list of current labels and compare against
      // what Ooyala says each video is using.
      $node_labels = ooyala_taxonomy_node_labels($node); // TODO FIXME
      $ooyala_labels = array();
      foreach ($video['labels'] as $olid => $label_name) {
        // Do not compare labels that aren't synced with Drupal.
        if (preg_match($label_filter, $label_name)) {
          $ooyala_labels[] = $olid;
        }
      }

      $diff1 = array_diff($node_labels, $ooyala_labels);
      $diff2 = array_diff($ooyala_labels, $node_labels);

      // If there is any difference, replace with the Ooyala labels.
      if ($diff1 || $diff2) {
        $term_list = array();
        // Keep the list of terms that are not synced with Ooyala at all.
        $tids = ooyala_taxonomy_tids_for_nid($node);
        foreach ($tids as $tid => $term) {
          if (!isset($ooyala_taxonomy[$term->vid])) {
            $term_list[] = $tid;
          }
        }
        // Add the new Ooyala labels as terms.
        foreach ($ooyala_labels as $olid) {
          $term_list[] = ooyala_taxonomy_term_load(NULL, $olid);
        }
        $node->taxonomy = $term_list;
        $node->pulled_from_ooyala = TRUE; // Mark this node as changed.
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ooyala_taxonomy_form_ooyala_settings_form_alter(&$form, &$form_state) {
  module_load_include('inc', 'ooyala_taxonomy', 'ooyala_taxonomy.pages');
  _ooyala_taxonomy_settings_form($form, $form_state);
}

/**
 * Fetch a list of all Ooyala labels that can be derived from a node's taxonomy.
 *
 * This function is used when saving a node and Taxonomy sycnronization is
 * enabled. The list of labels is then compared against the Ooyala Backlot video
 * and labels are added/removed to correspond with the synced vocabularies.
 *
 * @param $node
 *   A full node object.
 */
function ooyala_taxonomy_node_labels($node) {
  $labels = array();

  $ooyala_vocabularies = array_filter(variable_get('ooyala_taxonomy', array()));
  if (empty($ooyala_vocabularies)) {
    return $labels;
  }

  module_load_include('inc', 'ooyala', 'includes/ooyala.api');
  module_load_include('inc', 'ooyala_taxonomy');

  foreach ($ooyala_vocabularies as $vid => $olid) {
    $vocabulary_label = ooyala_api_label_name($olid);

    $fields_to_check = ooyala_taxonomy_get_taxonomy_fields();
    $terms = array();
    foreach ($fields_to_check as $field_name) {
      if (!empty($node->{$field_name})) {
        foreach ($node->{$field_name}[LANGUAGE_NONE] as $term) {
          $terms[$term['tid']] = ooyala_taxonomy_term_load($term['tid']);
        }
      }
    }

    // Loop through all terms and build a list of labels.
    foreach ($terms as $tid => $term) {
      // Use the label ID if available, as it tends to be more accurate.
      if (isset($term->olid)) {
        $labels[] = $term->olid;
      }
      // Otherwise return a label as a path, assume it will be inserted.
      else {
        $parents = taxonomy_get_parents($tid);
        $term_label = $vocabulary_label;
        foreach ($parents as $parent_term) {
          $term_label .= '/' . $parent_term->name;
        }
        $term_label .= '/' . $term->name;
        $labels[] = $term_label;
      }
    }
  }

  return $labels;
}

/**
 * Return the taxonomy field(s)
 *
 * @return
 * The name of the field(s) we should put terms in
 */
function ooyala_taxonomy_get_taxonomy_fields() {
  $fields = field_info_fields();
  $field_names = array_keys($fields);
  
  foreach ($field_names as $name) {
    if ($fields[$name]['type'] == 'taxonomy_term_reference') {
      $taxonomy_fields[] = $fields[$name]['field_name'];
    }
  }

  return $taxonomy_fields;
}

/**
 * For a given node, return the taxonomy term ids for the node
 *
 * @param $node
 * The node in question.
 * @return
 * An array of tids
 */
function ooyala_taxonomy_tids_for_nid($node) {
  $fields = field_info_fields();
  $field_names = array_keys($fields);
  
  foreach ($field_names as $name) {
    if (isset($node->{$name}) && $fields[$name]['type'] == 'taxonomy_term_reference') {
      if (isset($node->{$name}[LANGUAGE_NONE]) && is_array($node->{$name}[LANGUAGE_NONE])) {
        foreach ($node->{$name}[LANGUAGE_NONE] as $tid) {
          $tids[$tid['tid']] = $tid['tid'];
        }
      }
    }
  }
  
  return $tids;
}
