<?php

/**
 * Implementation of hook_js_alter();
 */
function summary_required_js_alter(&$javascript) {
  // remove the JS that does the show/hide summary
  unset($javascript['modules/field/modules/text/text.js']);
}

/**
 * Implementation of hook_node_validate();
 */
function summary_required_node_validate($node, $form, &$form_state) {
//  if (!isset($node->body['und'][0]['summary']) || !$node->body['und'][0]['summary']) {
//    form_set_error('Node', t('You must enter a summary!'));
//  } 
}