<?php
/**
 * @file
 * Code for the Enterprise Events feature.
 */

include_once 'enterprise_events.features.inc';

/**
 * Implements hook_ds_fields_info().
 */
function enterprise_events_ds_fields_info($entity_type) {
  $node = array();
  $node['ical_feed'] = array(
    'title' => t('iCal Feed'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit' => array('enterprise_event|*'),
    'function' => 'enterprise_events_ical_feed',
    'properties' => array(),
  );
  return array('node' => $node);
}

/**
 * Callback for enterprise events ical feed
 */
function enterprise_events_ical_feed($variables) {
  $entity = $variables['entity'];
  return theme('icon', array('bundle' => 'enterprise_base', 'icon' => 'oeicon-calendar')) . l('Add to my calendar', 'node/' . $entity->nid . '/ical.ics');
}

/**
 * Implements hook_ds_classes_alter().
 * Provide the necessary classes for blog types.
 */
function enterprise_events_ds_classes_alter(&$classes, $name) {
  if ('ds_classes_regions' === $name) {
    $classes['style-event-full'] = t('Event: Full');
    $classes['style-event-teaser'] = t('Event: Teaser');
    $classes['style-event-upcoming'] = t('Event: Upcoming');
  }
}
